kind = "web"
previewPath = "/"
title = "CabsOnline"
version = "1.0.0"
id = "artifacts/cabs-online"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 21739

[services.development]
run = "pnpm --filter @workspace/cabs-online run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/cabs-online", "run", "build" ]
publicDir = "artifacts/cabs-online/dist"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "21739"
BASE_PATH = "/"
